<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>$(CurrentTargetFramework)</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.StackExchange.Redis" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Orleans.Client" />
		<PackageReference Include="Microsoft.Orleans.Clustering.Redis" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Orleans.Streaming.RabbitMQ\Orleans.Streaming.RabbitMQ.csproj" />
	  <ProjectReference Include="..\..\Common\Common.csproj" />
	  <ProjectReference Include="..\AspireHost\AspireHost\AspireHost.ServiceDefaults\AspireHost.ServiceDefaults.csproj" />
	  <ProjectReference Include="..\GrainInterfaces\GrainInterfaces.csproj" />
	</ItemGroup>
</Project>
