<Project>
	<PropertyGroup>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup>
		<DefaultTargetFramework>net8.0</DefaultTargetFramework>
		<CompatibleTargetFramework>netstandard2.0</CompatibleTargetFramework>
	</PropertyGroup>
</Project>