<Project>
	<PropertyGroup>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup>
		<LongTermSupportTargetFramework>net8.0</LongTermSupportTargetFramework>
		<CurrentTargetFramework>net10.0</CurrentTargetFramework>
		<DefaultTargetFrameworks>$(LongTermSupportTargetFramework);$(CurrentTargetFramework)</DefaultTargetFrameworks>
	</PropertyGroup>
</Project>