<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.Orleans" Version="13.1.0" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.1.0" />
    <PackageVersion Include="Aspire.StackExchange.Redis" Version="13.1.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.2.0" />
    <PackageVersion Include="Microsoft.Orleans.Client" Version="9.2.1" />
    <PackageVersion Include="Microsoft.Orleans.Clustering.Redis" Version="9.2.1" />
    <PackageVersion Include="Microsoft.Orleans.Persistence.Memory" Version="9.2.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="Microsoft.Orleans.Sdk" Version="9.2.1" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="9.2.1" />
    <PackageVersion Include="Microsoft.Orleans.Streaming" Version="9.2.1" />
    <PackageVersion Include="Microsoft.Orleans.TestingHost" Version="9.2.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
    <PackageVersion Include="Testcontainers" Version="4.6.0" />
    <PackageVersion Include="Testcontainers.RabbitMq" Version="4.6.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="Xunit.Extensions.Logging" Version="1.1.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>
</Project>