<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(CurrentTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>65f49ad8-d1f5-4db3-94c9-9bf53fc05d68</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Orleans" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Client\Client.csproj" />
    <ProjectReference Include="..\..\..\SiloHost\SiloHost.csproj" />
  </ItemGroup>

</Project>
